# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fe_service_pb2 as fe__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fe_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ForgettingEngineStub(object):
    """FE 遗忘引擎服务 — 对应 knownot.cc:50052
    严格对齐 forgetting-engine MCP 工具接口

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handshake = channel.unary_unary(
                '/forgetting_engine.v1.ForgettingEngine/Handshake',
                request_serializer=fe__service__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=fe__service__pb2.HandshakeResponse.FromString,
                _registered_method=True)
        self.Retrieve = channel.unary_unary(
                '/forgetting_engine.v1.ForgettingEngine/Retrieve',
                request_serializer=fe__service__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=fe__service__pb2.RetrieveResponse.FromString,
                _registered_method=True)
        self.Ingest = channel.unary_unary(
                '/forgetting_engine.v1.ForgettingEngine/Ingest',
                request_serializer=fe__service__pb2.IngestRequest.SerializeToString,
                response_deserializer=fe__service__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.IngestFeatures = channel.unary_unary(
                '/forgetting_engine.v1.ForgettingEngine/IngestFeatures',
                request_serializer=fe__service__pb2.IngestFeaturesRequest.SerializeToString,
                response_deserializer=fe__service__pb2.IngestFeaturesResponse.FromString,
                _registered_method=True)
        self.UpdateKinProfile = channel.unary_unary(
                '/forgetting_engine.v1.ForgettingEngine/UpdateKinProfile',
                request_serializer=fe__service__pb2.UpdateKinProfileRequest.SerializeToString,
                response_deserializer=fe__service__pb2.UpdateKinProfileResponse.FromString,
                _registered_method=True)


class ForgettingEngineServicer(object):
    """FE 遗忘引擎服务 — 对应 knownot.cc:50052
    严格对齐 forgetting-engine MCP 工具接口

    """

    def Handshake(self, request, context):
        """握手配对
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """检索记忆上下文
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ingest(self, request, context):
        """写入记忆
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestFeatures(self, request, context):
        """写入用户特征
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateKinProfile(self, request, context):
        """更新 Kin 画像
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForgettingEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=fe__service__pb2.HandshakeRequest.FromString,
                    response_serializer=fe__service__pb2.HandshakeResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=fe__service__pb2.RetrieveRequest.FromString,
                    response_serializer=fe__service__pb2.RetrieveResponse.SerializeToString,
            ),
            'Ingest': grpc.unary_unary_rpc_method_handler(
                    servicer.Ingest,
                    request_deserializer=fe__service__pb2.IngestRequest.FromString,
                    response_serializer=fe__service__pb2.IngestResponse.SerializeToString,
            ),
            'IngestFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestFeatures,
                    request_deserializer=fe__service__pb2.IngestFeaturesRequest.FromString,
                    response_serializer=fe__service__pb2.IngestFeaturesResponse.SerializeToString,
            ),
            'UpdateKinProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateKinProfile,
                    request_deserializer=fe__service__pb2.UpdateKinProfileRequest.FromString,
                    response_serializer=fe__service__pb2.UpdateKinProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forgetting_engine.v1.ForgettingEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forgetting_engine.v1.ForgettingEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ForgettingEngine(object):
    """FE 遗忘引擎服务 — 对应 knownot.cc:50052
    严格对齐 forgetting-engine MCP 工具接口

    """

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgetting_engine.v1.ForgettingEngine/Handshake',
            fe__service__pb2.HandshakeRequest.SerializeToString,
            fe__service__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgetting_engine.v1.ForgettingEngine/Retrieve',
            fe__service__pb2.RetrieveRequest.SerializeToString,
            fe__service__pb2.RetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ingest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgetting_engine.v1.ForgettingEngine/Ingest',
            fe__service__pb2.IngestRequest.SerializeToString,
            fe__service__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgetting_engine.v1.ForgettingEngine/IngestFeatures',
            fe__service__pb2.IngestFeaturesRequest.SerializeToString,
            fe__service__pb2.IngestFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateKinProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgetting_engine.v1.ForgettingEngine/UpdateKinProfile',
            fe__service__pb2.UpdateKinProfileRequest.SerializeToString,
            fe__service__pb2.UpdateKinProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
